import { access, mkdir, readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { expect, test } from "@playwright/test";

const graphPath = resolve(".tmp/live-project-map/graph.json");
const outputDir = resolve(".tmp/playwright-visual/live-label-comparison");

const presets = [
  ["01-systems-current", (owner) => `/u/?username=${encodeURIComponent(owner)}&style=galaxy-systems`],
  ["02-hybrid-current", (owner) => `/u/?username=${encodeURIComponent(owner)}&style=galaxy-hybrid`],
  ["03-soft-systems-adaptive-labels", (owner) => `/u/?username=${encodeURIComponent(owner)}&style=galaxy-systems&labels=soft`],
  ["04-cluster-current", (owner) => `/cluster/?username=${encodeURIComponent(owner)}&style=cluster`],
];

async function hasLiveGraph() {
  try { await access(graphPath); return true; } catch { return false; }
}

async function routeGraph(page, graph) {
  await page.route("**/project-map/graph.json", async (route) => {
    await route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify(graph) });
  });
}

async function waitForMap(page) {
  await expect(page.locator("#status")).toBeHidden();
  await page.waitForFunction(() => typeof state !== "undefined" && state.graph && Array.isArray(state.nodes) && state.nodes.length > 0);
  await page.waitForTimeout(180);
}

test("capture current and adaptive text-label strategies on the same live graph", async ({ page }) => {
  test.skip(!(await hasLiveGraph()), "live graph fixture is only generated by the comparison CI branch");
  const graph = JSON.parse(await readFile(graphPath, "utf8"));
  const owner = String(graph.owner || "").trim();
  expect(owner).toBeTruthy();
  await mkdir(outputDir, { recursive: true });
  await page.setViewportSize({ width: 960, height: 600 });
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.addInitScript({ path: resolve("scripts/public-soft-labels.js") });

  const repoNames = graph.nodes.filter((node) => node?.type === "repository").map((node) => node.label);
  const preferred = repoNames.find((name) => name === "FTBPublicClaims") || repoNames[0] || "";

  for (const [name, urlFor] of presets) {
    await routeGraph(page, graph);
    await page.goto(urlFor(owner));
    await waitForMap(page);

    const canvas = page.locator("#galaxy");
    await canvas.screenshot({ path: resolve(outputDir, `${name}-overview.png`) });

    if (preferred) {
      const search = page.locator("#search");
      await search.fill(preferred);
      await page.waitForTimeout(100);
      await canvas.screenshot({ path: resolve(outputDir, `${name}-focus-${preferred}.png`) });
      await search.fill("");
    }

    if (name.includes("soft-systems")) {
      const debug = await page.evaluate(() => window.ProjectMapSoftLabelDebug || null);
      expect(debug).toBeTruthy();
      expect(debug.repoLabels).toBeGreaterThan(0);
      expect(debug.repoLabels).toBeLessThanOrEqual(debug.repoBudget);
    }

    await page.unrouteAll({ behavior: "wait" });
  }
});
