const USERNAME_RE=/^[A-Za-z0-9](?:[A-Za-z0-9-]{0,37}[A-Za-z0-9])?$/;
function normalizeUsername(value){const username=String(value||'').trim().toLowerCase();if(!USERNAME_RE.test(username))throw new Error('Invalid GitHub username');return username}
const query=new URL(location.href).searchParams;let username='';
const canvas=document.getElementById('galaxy');const ctx=canvas.getContext('2d');const tip=document.getElementById('tip');const errorBox=document.getElementById('error');const errorText=document.getElementById('errorText');const setup=document.getElementById('setup');
function showError(message){errorText.textContent=message;errorBox.classList.add('visible')}
try{username=normalizeUsername(query.get('username'));document.title=username+' · Project Galaxy';document.getElementById('title').textContent=username+' · Interactive Project Map';canvas.setAttribute('aria-label','Interactive project galaxy for '+username);const setupUrl=new URL('../',location.href);setupUrl.searchParams.set('username',username);setup.href=setupUrl.toString()}catch(error){showError(error.message)}
let graph=null,nodes=[],edges=[],drag=null,pan={x:0,y:0},zoom=1,last={x:0,y:0},down={x:0,y:0},panning=false,pinchDistance=0;const pointers=new Map();
function h(s){let x=2166136261;for(let i=0;i<s.length;i++){x^=s.charCodeAt(i);x=Math.imul(x,16777619)}return x>>>0}
function color(s){return'hsl('+(h(s)%360)+' 72% 66%)'}
function cleanText(value,max){return typeof value==='string'?value.slice(0,max):''}
function safeRepoUrl(value,name){if(typeof value!=='string')return null;try{const u=new URL(value);if(u.protocol!=='https:'||u.hostname!=='github.com')return null;const p=u.pathname.split('/').filter(Boolean).map(decodeURIComponent);if(p.length<2||p[0].toLowerCase()!==username||p[1].toLowerCase()!==name.toLowerCase())return null;return'https://github.com/'+encodeURIComponent(username)+'/'+encodeURIComponent(name)}catch{return null}}
function sanitizeGraph(value){if(!value||typeof value!=='object'||String(value.owner||'').toLowerCase()!==username||!Array.isArray(value.nodes)||value.nodes.length>520)return null;const safeNodes=[],ids=new Set();for(const raw of value.nodes){if(!raw||typeof raw!=='object'||!['owner','group','repository'].includes(raw.type))continue;const id=cleanText(raw.id,180),label=cleanText(raw.label,120);if(!id||!label||ids.has(id))continue;let node={id,label,type:raw.type};if(raw.type==='owner'){node.url='https://github.com/'+encodeURIComponent(username)}else if(raw.type==='group'){node.repositoryCount=Number.isFinite(raw.repositoryCount)?Math.max(0,Math.floor(raw.repositoryCount)):0}else{if(!/^[A-Za-z0-9._-]{1,100}$/.test(label))continue;const url=safeRepoUrl(raw.url,label);if(!url)continue;node={...node,url,description:cleanText(raw.description,2000),language:typeof raw.language==='string'?raw.language.slice(0,100):null,stars:Number.isFinite(raw.stars)?Math.max(0,Math.floor(raw.stars)):0,forks:Number.isFinite(raw.forks)?Math.max(0,Math.floor(raw.forks)):0,fork:raw.fork===true,archived:raw.archived===true,groupId:cleanText(raw.groupId,120),groupLabel:cleanText(raw.groupLabel,120)}}ids.add(id);safeNodes.push(node)}const safeEdges=Array.isArray(value.edges)?value.edges.filter(e=>e&&typeof e==='object'&&ids.has(e.source)&&ids.has(e.target)).slice(0,1200).map(e=>({source:e.source,target:e.target,type:cleanText(e.type,40)})):[];if(!safeNodes.some(n=>n.type==='owner'))safeNodes.unshift({id:'user:'+username,label:username,type:'owner',url:'https://github.com/'+encodeURIComponent(username)});return{owner:username,generatedAt:cleanText(value.generatedAt,64),repositoryCount:safeNodes.filter(n=>n.type==='repository').length,groupCount:safeNodes.filter(n=>n.type==='group').length,nodes:safeNodes,edges:safeEdges}}
function resize(){const d=devicePixelRatio||1;canvas.width=innerWidth*d;canvas.height=innerHeight*d;ctx.setTransform(d,0,0,d,0,0);if(graph)build(graph);draw()}
function build(g){graph=g;const groups=g.nodes.filter(n=>n.type==='group'),repos=g.nodes.filter(n=>n.type==='repository');nodes=[];const cx=innerWidth/2,cy=innerHeight/2,R=Math.min(innerWidth,innerHeight),owner=g.nodes.find(n=>n.type==='owner');if(owner)nodes.push({...owner,x:cx,y:cy,r:26});groups.forEach((group,i)=>{const a=-Math.PI/2+Math.PI*2*i/Math.max(groups.length,1);nodes.push({...group,x:cx+Math.cos(a)*R*.25,y:cy+Math.sin(a)*R*.25,r:8});const m=repos.filter(r=>r.groupId&&group.id==='group:'+r.groupId);m.forEach((repo,j)=>{const spread=Math.min(.8,.18+m.length*.035),off=m.length<2?0:(j/(m.length-1)-.5)*spread,jitter=((h(repo.id)%1000)/1000-.5)*.09,rr=R*(.35+((h(repo.id+':r')%1000)/1000-.5)*.07),aa=a+off+jitter;nodes.push({...repo,x:cx+Math.cos(aa)*rr,y:cy+Math.sin(aa)*rr,r:Math.min(12,5+Math.log2((repo.stars||0)+1)*1.5)})})});edges=g.edges}
function world(p){return{x:(p.x-pan.x)/zoom,y:(p.y-pan.y)/zoom}}
function hit(x,y){const w=world({x,y});for(let i=nodes.length-1;i>=0;i--){const n=nodes[i],r=Math.max(n.r,9/zoom);if((w.x-n.x)**2+(w.y-n.y)**2<=r*r)return n}return null}
function pointDistance(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}function pointerPair(){const v=[...pointers.values()];return v.length>=2?[v[0],v[1]]:null}
function draw(){ctx.clearRect(0,0,innerWidth,innerHeight);ctx.fillStyle='#050811';ctx.fillRect(0,0,innerWidth,innerHeight);for(let i=0;i<100;i++){ctx.globalAlpha=.12+(h(username+':o:'+i)%40)/100;ctx.fillStyle='#c8d7f2';ctx.beginPath();ctx.arc(h(username+':x:'+i)%innerWidth,h(username+':y:'+i)%innerHeight,.4+(h(username+':r:'+i)%10)/10,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;if(!graph)return;const map=new Map(nodes.map(n=>[n.id,n]));ctx.save();ctx.translate(pan.x,pan.y);ctx.scale(zoom,zoom);ctx.strokeStyle='#344054';ctx.lineWidth=1/zoom;ctx.globalAlpha=.65;for(const e of edges){const a=map.get(e.source),b=map.get(e.target);if(!a||!b)continue;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}ctx.globalAlpha=1;for(const n of nodes){ctx.fillStyle=n.type==='owner'?color(n.label):color(n.language||n.groupLabel||n.label);ctx.globalAlpha=n.fork?.72:1;ctx.beginPath();ctx.arc(n.x,n.y,n.r,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;if(n.type==='owner'){ctx.strokeStyle=color(n.label);ctx.globalAlpha=.25;ctx.lineWidth=2/zoom;ctx.beginPath();ctx.arc(n.x,n.y,n.r+8,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1}if(zoom>.72||n.type!=='repository'){ctx.fillStyle=n.type==='group'?'#9aa7bd':'#eaf0ff';ctx.font=(n.type==='owner'?'700 15px':'11px')+' Inter,system-ui';ctx.textAlign='center';const text=n.label.length>26?n.label.slice(0,24)+'…':n.label;ctx.fillText(text,n.x,n.y+n.r+14)}}ctx.restore()}
function finishPointer(e,allowClick){const clicked=allowClick&&pointers.size===1&&pointers.has(e.pointerId)&&drag&&Math.hypot(e.clientX-down.x,e.clientY-down.y)<7?drag:null;pointers.delete(e.pointerId);if(pointers.size<2)pinchDistance=0;drag=null;panning=false;canvas.classList.remove('dragging');if(clicked&&clicked.url)open(clicked.url,'_blank','noopener')}
canvas.addEventListener('wheel',e=>{e.preventDefault();const before=world({x:e.clientX,y:e.clientY}),factor=Math.exp(-e.deltaY*.001);zoom=Math.max(.35,Math.min(4,zoom*factor));pan.x=e.clientX-before.x*zoom;pan.y=e.clientY-before.y*zoom;draw()},{passive:false});
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});tip.style.display='none';if(pointers.size===2){const pair=pointerPair();drag=null;panning=false;pinchDistance=pair?pointDistance(pair[0],pair[1]):0;return}if(pointers.size!==1)return;last={x:e.clientX,y:e.clientY};down={...last};drag=hit(e.clientX,e.clientY);panning=!drag;canvas.classList.add('dragging')});
canvas.addEventListener('pointermove',e=>{if(pointers.has(e.pointerId))pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){const pair=pointerPair();if(pair){const distance=pointDistance(pair[0],pair[1]),midpoint={x:(pair[0].x+pair[1].x)/2,y:(pair[0].y+pair[1].y)/2};if(pinchDistance>0&&distance>0){const before=world(midpoint);zoom=Math.max(.35,Math.min(4,zoom*(distance/pinchDistance)));pan.x=midpoint.x-before.x*zoom;pan.y=midpoint.y-before.y*zoom}pinchDistance=distance;draw()}return}if(drag&&pointers.size===1){const w=world({x:e.clientX,y:e.clientY});drag.x=w.x;drag.y=w.y;draw()}else if(panning&&pointers.size===1){pan.x+=e.clientX-last.x;pan.y+=e.clientY-last.y;last={x:e.clientX,y:e.clientY};draw()}else if(pointers.size===0){const hover=hit(e.clientX,e.clientY);if(hover){tip.style.display='block';tip.style.left=e.clientX+14+'px';tip.style.top=e.clientY+14+'px';tip.textContent=hover.type==='repository'?hover.label+(hover.language?' · '+hover.language:'')+(hover.stars!=null?' · ★ '+hover.stars:''):hover.label}else tip.style.display='none'}});
canvas.addEventListener('pointerup',e=>finishPointer(e,true));canvas.addEventListener('pointercancel',e=>finishPointer(e,false));canvas.addEventListener('lostpointercapture',e=>{if(pointers.has(e.pointerId))finishPointer(e,false)});addEventListener('resize',resize);resize();
if(username){const owner=encodeURIComponent(username);const graphUrl='https://raw.githubusercontent.com/'+owner+'/'+owner+'/HEAD/project-map/graph.json';fetch(graphUrl,{cache:'no-cache'}).then(r=>{if(!r.ok)throw new Error('graph.json returned '+r.status);return r.json()}).then(value=>{const clean=sanitizeGraph(value);if(!clean)throw new Error('graph.json failed validation');return clean}).then(build).then(draw).catch(error=>showError('Could not load '+username+'/'+username+'/project-map/graph.json. Run the setup workflow once, or regenerate it if the file is invalid. ('+error.message+')'))}
