const USERNAME_RE=/^[A-Za-z0-9](?:[A-Za-z0-9-]{0,37}[A-Za-z0-9])?$/;
const COMMIT_SHA_RE=/^[0-9a-f]{40}$/;
const CHECKOUT_SHA='3d3c42e5aac5ba805825da76410c181273ba90b1';
const DOWNLOAD_SHA='3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c';
const PROJECT_MAP_ACTION_REF='__PROJECT_MAP_ACTION_REF__';
const PROJECT_MAP_REUSABLE_REF='v1';
const WORKFLOW_PATH='.github/workflows/project-map.yml';
const STYLE_VALUES=new Set(['radial','galaxy-classic','galaxy-systems','galaxy-hybrid','obsidian','tree','treemap','timeline','cluster','sunburst','matrix','sankey']);
const form=document.getElementById('form'),usernameInput=document.getElementById('username'),themeInput=document.getElementById('theme'),styleInput=document.getElementById('mapStyle'),maxReposInput=document.getElementById('maxRepos'),forksInput=document.getElementById('forks'),archivedInput=document.getElementById('archived'),contributedInput=document.getElementById('contributed'),statusEl=document.getElementById('status'),resultEl=document.getElementById('result'),preview=document.getElementById('preview'),previewMessage=document.getElementById('previewMessage'),openMap=document.getElementById('openMap'),presetCards=[...document.querySelectorAll('[data-style-preset]')];
const guidedControlsAvailable=typeof document.querySelector==='function'&&typeof document.createElement==='function';
const actionsEl=guidedControlsAvailable?document.querySelector('.actions'):null;
const inertControl=()=>({dataset:{},hidden:true,href:'',textContent:'',addEventListener(){}});
const createProfileRepoLink=guidedControlsAvailable?document.createElement('a'):inertControl();
const addWorkflowButton=guidedControlsAvailable?document.createElement('button'):inertControl();
const runWorkflowLink=guidedControlsAvailable?document.createElement('a'):inertControl();
if(guidedControlsAvailable){createProfileRepoLink.id='createProfileRepoOnGitHub';createProfileRepoLink.className='button';createProfileRepoLink.target='_blank';createProfileRepoLink.rel='noopener';createProfileRepoLink.textContent='0 · No profile repo? Create it ↗';createProfileRepoLink.hidden=true;createProfileRepoLink.title='Create USERNAME/USERNAME as a public GitHub profile repository. Enable Add README on GitHub before creating it.';addWorkflowButton.id='addWorkflowOnGitHub';addWorkflowButton.className='button';addWorkflowButton.type='button';addWorkflowButton.textContent='1 · Add workflow on GitHub ↗';addWorkflowButton.hidden=true;runWorkflowLink.id='runWorkflowOnGitHub';runWorkflowLink.className='button';runWorkflowLink.target='_blank';runWorkflowLink.rel='noopener';runWorkflowLink.textContent='2 · Run first update ↗';runWorkflowLink.hidden=true;if(actionsEl){const copyWorkflowButton=actionsEl.querySelector('[data-copy="workflow"]');actionsEl.insertBefore(createProfileRepoLink,copyWorkflowButton);actionsEl.insertBefore(addWorkflowButton,copyWorkflowButton);actionsEl.insertBefore(runWorkflowLink,copyWorkflowButton);}}
function normalizeStyle(value){if(value==='galaxy')return'galaxy-systems';return STYLE_VALUES.has(value)?value:'radial';}
function normalizeGeneratorRef(value){const normalized=String(value||'').trim().toLowerCase();if(!normalized||normalized===PROJECT_MAP_REUSABLE_REF)return PROJECT_MAP_REUSABLE_REF;return COMMIT_SHA_RE.test(normalized)?normalized:null;}
function syncPresetCards(style){for(const card of presetCards){const selected=card.dataset.stylePreset===style;card.classList.toggle('is-selected',selected);card.setAttribute('aria-pressed',String(selected));}}
function values(){const username=usernameInput.value.trim().toLowerCase(),maxRepos=Math.max(1,Math.min(300,Math.round(Number(maxReposInput.value)||100))),style=normalizeStyle(styleInput?.value),generatorRef=normalizeGeneratorRef(new URL(location.href).searchParams.get('generator_ref'));return{username,theme:themeInput.value==='light'?'light':'dark',style,maxRepos,forks:forksInput.checked,archived:archivedInput.checked,contributed:contributedInput?.checked===true,generatorRef};}
function urls(v){const owner=encodeURIComponent(v.username),raw='https://raw.githubusercontent.com/'+owner+'/'+owner+'/HEAD/project-map';const dedicated=new Set(['radial','tree','treemap','timeline','cluster','sunburst','matrix','sankey']);const route=dedicated.has(v.style)?v.style+'/':'u/';const viewer=new URL(route,new URL('./',location.href));viewer.searchParams.set('username',v.username);viewer.searchParams.set('style',v.style);return{svg:raw+'/galaxy.svg',graph:raw+'/graph.json',viewer:viewer.toString()};}
function githubSetupUrls(username){const owner=encodeURIComponent(username),profile=new URL('https://github.com/new'),create=new URL('https://github.com/'+owner+'/'+owner+'/new/main');profile.searchParams.set('name',username);profile.searchParams.set('owner',username);profile.searchParams.set('visibility','public');profile.searchParams.set('description','GitHub profile for '+username);create.searchParams.set('filename',WORKFLOW_PATH);return{profile:profile.toString(),create:create.toString(),run:'https://github.com/'+owner+'/'+owner+'/actions/workflows/project-map.yml'};}
function workflowFor(v){const generatorRef=normalizeGeneratorRef(v.generatorRef)||PROJECT_MAP_REUSABLE_REF,policy=generatorRef===PROJECT_MAP_REUSABLE_REF?'stable-v1':'pinned-'+generatorRef;return['name: Update project map','# Project Map generator policy: '+policy,'# Stable generator baseline: nekomario28/interactive-project-map@'+PROJECT_MAP_ACTION_REF+' ; inner uses: nekomario28/interactive-project-map@'+PROJECT_MAP_ACTION_REF,'','on:','  workflow_dispatch:','  schedule:','    - cron: "37 3 * * *"','','permissions:','  contents: read','','jobs:','  generate:','    permissions:','      contents: read','    uses: nekomario28/interactive-project-map/.github/workflows/generate-project-map.yml@'+generatorRef,'    with:','      theme: '+v.theme,'      style: '+v.style,'      max_repos: "'+v.maxRepos+'"','      forks: '+v.forks,'      archived: '+v.archived,'      contributed: '+v.contributed,'','  publish:','    needs: generate','    runs-on: ubuntu-latest','    permissions:','      actions: read','      contents: write','    steps:','      - name: Checkout profile repository','        uses: actions/checkout@'+CHECKOUT_SHA+' # v7.0.1','','      - name: Download generated files','        uses: actions/download-artifact@'+DOWNLOAD_SHA+' # v8.0.1','        with:','          name: project-map-generated','          path: project-map','','      - name: Commit only when the generated map changed','        shell: bash','        run: |','          set -euo pipefail','          git add -- project-map/galaxy.svg project-map/graph.json','          if git diff --cached --quiet; then','            echo "Project map is already up to date."','            exit 0','          fi','          git config user.name "github-actions[bot]"','          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"','          git commit -m "chore: update project map"','          git push',''].join('\n');}
function hideGuidedControls(){createProfileRepoLink.hidden=true;addWorkflowButton.hidden=true;runWorkflowLink.hidden=true;}
function generate(){const v=values();maxReposInput.value=String(v.maxRepos);syncPresetCards(v.style);if(!v.generatorRef){statusEl.textContent='generator_ref must be v1 or a full 40-character commit SHA.';statusEl.classList.add('error');resultEl.classList.remove('visible');hideGuidedControls();return;}if(!USERNAME_RE.test(v.username)){statusEl.textContent='Enter a valid GitHub username.';statusEl.classList.add('error');resultEl.classList.remove('visible');hideGuidedControls();return;}const u=urls(v),github=githubSetupUrls(v.username),workflow=workflowFor(v),html='<p align="center">\n  <a href="'+u.viewer+'">\n    <img width="740" src="'+u.svg+'" alt="'+v.username+' project map" />\n  </a>\n</p>',md='[!['+v.username+' project map]('+u.svg+')]('+u.viewer+')';document.getElementById('workflow').value=workflow;document.getElementById('readmeHtml').value=html;document.getElementById('readmeMarkdown').value=md;document.getElementById('staticUrls').value='SVG: '+u.svg+'\nGraph: '+u.graph+'\nInteractive: '+u.viewer;openMap.href=u.viewer;createProfileRepoLink.href=github.profile;createProfileRepoLink.hidden=false;addWorkflowButton.dataset.githubUrl=github.create;addWorkflowButton.hidden=false;runWorkflowLink.href=github.run;runWorkflowLink.hidden=false;preview.classList.remove('ready');previewMessage.textContent='Checking for an existing generated SVG…';preview.src=u.svg;resultEl.classList.add('visible');statusEl.textContent='Setup generated. Contributed is '+(v.contributed?'enabled: bounded public work in repositories owned by others will be included.':'off by default.')+' If '+v.username+'/'+v.username+' does not exist, use Step 0 and enable Add README on GitHub. Then Step 1 copies the workflow; paste and commit it, then use Step 2 once.';statusEl.classList.remove('error');const share=new URL(location.href);share.search='';share.searchParams.set('username',v.username);share.searchParams.set('theme',v.theme);share.searchParams.set('style',v.style);share.searchParams.set('max_repos',String(v.maxRepos));share.searchParams.set('forks',String(v.forks));share.searchParams.set('archived',String(v.archived));share.searchParams.set('contributed',String(v.contributed));if(v.generatorRef!==PROJECT_MAP_REUSABLE_REF)share.searchParams.set('generator_ref',v.generatorRef);history.replaceState(null,'',share);}
addWorkflowButton.addEventListener('click',async()=>{const target=document.getElementById('workflow'),githubUrl=addWorkflowButton.dataset.githubUrl;if(!target||!githubUrl)return;let copied=false;let clipboardWrite=null;try{clipboardWrite=navigator.clipboard.writeText(target.value);}catch{clipboardWrite=null;}if(guidedControlsAvailable){const anchor=document.createElement('a');anchor.href=githubUrl;anchor.target='_blank';anchor.rel='noopener';anchor.click();}if(clipboardWrite){try{await clipboardWrite;copied=true;}catch{copied=false;}}if(!copied){target.select();copied=document.execCommand('copy');}addWorkflowButton.textContent=copied?'Copied · GitHub opened ↗':'GitHub opened ↗';statusEl.textContent=copied?'Workflow copied. In GitHub, paste it into '+WORKFLOW_PATH+', then Commit changes. Return here and use Step 2.':'GitHub opened. Copy the workflow below, paste it into '+WORKFLOW_PATH+', then Commit changes.';setTimeout(()=>{addWorkflowButton.textContent='1 · Add workflow on GitHub ↗';},1800);});
for(const card of presetCards)card.addEventListener('click',()=>{const style=normalizeStyle(card.dataset.stylePreset);if(styleInput)styleInput.value=style;syncPresetCards(style);});if(styleInput)styleInput.addEventListener('change',()=>syncPresetCards(normalizeStyle(styleInput.value)));form.addEventListener('submit',event=>{event.preventDefault();generate();});preview.addEventListener('load',()=>{preview.classList.add('ready');previewMessage.textContent='Existing static SVG found in the profile repository.';});preview.addEventListener('error',()=>{preview.classList.remove('ready');previewMessage.textContent='No static SVG yet. Run the generated workflow once, then reload this page.';});for(const button of document.querySelectorAll('[data-copy]'))button.addEventListener('click',async()=>{const target=document.getElementById(button.dataset.copy);if(!target)return;try{await navigator.clipboard.writeText(target.value);const old=button.textContent;button.textContent='Copied';setTimeout(()=>button.textContent=old,1200);}catch{target.select();document.execCommand('copy');}});
const initial=new URL(location.href).searchParams;if(initial.has('username')){usernameInput.value=initial.get('username')||'';themeInput.value=initial.get('theme')==='light'?'light':'dark';if(styleInput)styleInput.value=normalizeStyle(initial.get('style'));maxReposInput.value=initial.get('max_repos')||'100';forksInput.checked=initial.get('forks')!=='false';archivedInput.checked=initial.get('archived')==='true';if(contributedInput)contributedInput.checked=initial.get('contributed')==='true';syncPresetCards(normalizeStyle(styleInput?.value));generate();}else syncPresetCards(normalizeStyle(styleInput?.value));